name: Unity Build and Deploy

on:
  push:
    branches: 
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Unity Build
      uses: game-ci/unity-builder@v2.0.3
      env:
        UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
        UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
      with:
        targetPlatform: WebGL
    - name: Save Build
      uses: actions/upload-artifact@v2
      with:
        name: Build
        path: build
    - uses: actions/cache@v2
      with:
        path: Library
        key: Library-Workflow-TargetPlatform
        restore-keys: |
          Library-Workflow-
          Library-
